name: ${PROJECT_MODE}-${PROJECT_NAME} 

services: 
  # --- MAIN DATABASE CONFIGURATION --- # 
  db-main: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_db-main
    build: 
      context: ./db-main
      dockerfile: Dockerfile
      args: 
        DB_MAIN_VERSION: ${DB_MAIN_VERSION}
    restart: unless-stopped 
    env_file:
      - ../../../.env 
      - .env
    user: root 
    command: sh /home/postgres/main/start.sh
    volumes: 
      - ../../:/home/postgres/context
      - db-main:/var/lib/postgres/data
      - ./db-main:/home/postgres/main
      - ./@certs:/home/postgres/raw-certs
    networks: 
      - project

  # --- CACHE DATABASE CONFIGURATION --- # 
  db-cache: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_db-cache
    build: 
      context: ./db-cache
      dockerfile: Dockerfile
      args: 
        DB_CACHE_VERSION: ${DB_CACHE_VERSION}
    restart: unless-stopped 
    env_file:
      - ../../../.env 
      - .env
    user: root 
    command: sh /home/postgres/main/start.sh
    volumes: 
      - ../../:/home/postgres/context
      - db-cache:/var/lib/postgres/data
      - ./db-cache:/home/postgres/main
      - ./@certs:/home/postgres/raw-certs
    networks: 
      - project

  # --- QUEUE DATABASE CONFIGURATION --- # 
  db-queue: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_db-queue
    build: 
      context: ./db-queue
      dockerfile: Dockerfile
      args: 
        DB_QUEUE_VERSION: ${DB_QUEUE_VERSION}
    restart: unless-stopped 
    env_file:
      - ../../../.env 
      - .env
    user: root 
    command: sh /home/postgres/main/start.sh
    volumes: 
      - ../../:/home/postgres/context
      - db-queue:/var/lib/postgres/data
      - ./db-queue:/home/postgres/main
      - ./@certs:/home/postgres/raw-certs
    networks: 
      - project

  # --- SET UP ADMINER --- # 
  adminer:
    build: 
      context: ./adminer
      dockerfile: Dockerfile
      args: 
        ADMINER_PHP_VERSION: ${ADMINER_PHP_VERSION}
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_adminer
    volumes: 
      - ./adminer/app:/var/www/html/
    networks:
      - project

  adminer-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_adminer-server
    env_file:
      - ../../../.env 
      - .env
    image: ${ADMINER_NGINX_VERSION}
    volumes:
      - ./adminer/app:/var/www/html/
      - ./adminer/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on: 
      - adminer
    networks:
      - project

  # --- SET UP MAILPIT --- # 
  mailpit: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_mailpit
    build: 
      context: ./mailpit
      dockerfile: Dockerfile
      args: 
        MAILPIT_VERSION: ${MAILPIT_VERSION}
        MAILPIT_AUTH: 1
    env_file:
      - ../../../.env 
      - .env
    environment:
      MAILPIT_UI_BIND: 0.0.0.0:8025 
      MAILPIT_SMTP_BIND: 0.0.0.0:1025S
    volumes:
      - mailpit-data:/data
    networks: 
      - project

  mailpit-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_mailpit-server
    env_file:
      - ../../../.env 
      - .env
    image: ${MAILPIT_NGINX_VERSION}
    volumes:
      - ./mailpit/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - mailpit
    networks:
      - project

  # --- SET UP BACKEND --- # 
  backend: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_backend
    env_file:
      - ../../../.env 
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args: 
        BACKEND_PHP_VERSION: ${BACKEND_PHP_VERSION}
    working_dir: /home/app/source
    command: sh /home/app/main/start.sh
    volumes: 
      - ../../../source/backend:/home/app/source
      - ./backend:/home/app/main/
      - ./@certs:/certs
    depends_on: 
      - db-main
      - db-cache
      - db-queue
    networks:
      - project

  backend-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_backend-server
    env_file:
      - ../../../.env 
      - .env
    image: ${BACKEND_NGINX_VERSION}
    volumes:
      - ./backend/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - backend
    networks:
      - project

  # --- SET UP QUEUE ---  #
  queue: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_queue
    env_file:
      - ../../../.env 
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args: 
        BACKEND_PHP_VERSION: ${BACKEND_PHP_VERSION}
    working_dir: /home/app/source
    command: sh /home/app/main/start.sh
    volumes: 
      - ../../../source/backend:/home/app/source
      - ./queue:/home/app/main/
    depends_on: 
      - db-main
      - db-cache
      - db-queue
      - backend-server
    networks:
      - project
      
  # --- SET UP FRONTEND (WEB) --- # 
  frontend-web: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_frontend-web
    env_file:
      - ../../../.env 
      - .env
    build: 
      context: ./frontend-web
      dockerfile: Dockerfile
      args: 
        FRONTEND_WEB_NODE_VERSION: ${FRONTEND_WEB_NODE_VERSION}
    working_dir: /home/app/source
    command: sh /home/app/main/start.sh
    volumes: 
      - ../../../source/frontend-web:/home/app/source
      - ./frontend-web:/home/app/main/
    depends_on: 
      - backend-server
    networks:
      - project
  
  frontend-web-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_frontend-web-server
    env_file:
      - ../../../.env 
      - .env
    image: ${FRONTEND_WEB_NGINX_VERSION}
    volumes:
      - ./frontend-web/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - frontend-web
    networks:
      - project

  # --- SET UP FRONTEND (MOBILE) --- # 
  frontend-mobile:
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_frontend-mobile
    env_file:
      - ../../../.env 
      - .env
    build: 
      context: ./frontend-mobile
      dockerfile: Dockerfile
      args: 
        FRONTEND_MOBILE_NODE_VERSION: ${FRONTEND_MOBILE_NODE_VERSION}
    working_dir: /home/app/source
    command: sh /home/app/main/start.sh
    volumes: 
      - ../../../source/frontend-mobile:/home/app/source
      - ./frontend-mobile:/home/app/main/
    depends_on: 
      - backend-server
    networks:
      - project
  
  frontend-mobile-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_frontend-mobile-server
    env_file:
      - ../../../.env 
      - .env
    image: ${FRONTEND_MOBILE_NGINX_VERSION}
    volumes:
      - ./frontend-mobile/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - frontend-mobile
    networks:
      - project

  # --- SET UP WEBSOCKETS --- # 
  websockets: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_websockets
    env_file:
      - ../../../.env 
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args: 
        BACKEND_PHP_VERSION: ${BACKEND_PHP_VERSION}
    working_dir: /home/app/source
    command: sh /home/app/main/start.sh
    volumes: 
      - ../../../source/backend:/home/app/source
      - ./websockets:/home/app/main/
    depends_on: 
      - db-cache
      - db-main
      - db-queue
      - backend-server
    networks:
      - project

  websockets-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_websockets-server
    env_file:
      - ../../../.env 
      - .env
    image: ${WEBSOCKETS_NGINX_VERSION}
    volumes:
      - ./websockets/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - websockets
    networks:
      - project      


# --- SETUP NETWORKS --- #
networks:
  project:
    driver: bridge

# --- SETUP VOLUMES --- # 
volumes: 
  db-main:  
    driver: local 
  db-cache: 
    driver: local 
  db-queue: 
    driver: local
  mailpit-data:
    driver: local