#!/bin/bash
source .env
source .dkhfst/docker/${PROJECT_MODE}/.env

# PROCESS ARGUMENTS #
for i in "$@"; do
    if [[ "$i" == "--" ]]; then
        break
    fi
done

# Determine whether to use sudo
if command -v sudo >/dev/null 2>&1; then
    DOCKER_CMD="sudo docker compose"
else
    DOCKER_CMD="docker compose"
fi

# RUN COMMAND
$DOCKER_CMD \
    --env-file .env \
    --env-file .dkhfst/docker/${PROJECT_MODE}/.env \
    --file ./.dkhfst/docker/${PROJECT_MODE}/docker-compose.yml \
    "$@"
