#!/bin/bash
source .env
source .dkhfst/docker/${PROJECT_MODE}/.env

# PROCESS ARGUMENTS #
for i in "$@"; do
    if [[ "$i" == "--" ]]; then
        break
    fi
done

# RUN COMMAND # 
sudo docker compose \
    --env-file .env \
    --env-file .dkhfst/docker/${PROJECT_MODE}/.env \
    --file ./.dkhfst/docker/${PROJECT_MODE}/docker-compose.yml \
    "$@"
