name: ${PROJECT_MODE}-${PROJECT_NAME} 

services: 
  # --- MAIN DATABASE CONFIGURATION --- # 
  db-main: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_db-main
    build: 
      context: ./db-main
      dockerfile: Dockerfile
    restart: unless-stopped 
    env_file:
      - ../../../.env 
      - .env
    user: root 
    command: sh /home/postgres/main/start.sh
    volumes: 
      - ../../:/home/postgres/context
      - db-main:/var/lib/postgres/data
      - ./db-main:/home/postgres/main
      - ./@certs:/home/postgres/raw-certs
    networks: 
      - project

  # --- CACHE DATABASE CONFIGURATION --- # 
  db-cache: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_db-cache
    build: 
      context: ./db-cache
      dockerfile: Dockerfile
    restart: unless-stopped 
    env_file:
      - ../../../.env 
      - .env
    user: root 
    command: sh /home/postgres/main/start.sh
    volumes: 
      - ../../:/home/postgres/context
      - db-cache:/var/lib/postgres/data
      - ./db-cache:/home/postgres/main
      - ./@certs:/home/postgres/raw-certs
    networks: 
      - project

  # --- QUEUE DATABASE CONFIGURATION --- # 
  db-queue: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_db-queue
    build: 
      context: ./db-queue
      dockerfile: Dockerfile
    restart: unless-stopped 
    env_file:
      - ../../../.env 
      - .env
    user: root 
    command: sh /home/postgres/main/start.sh
    volumes: 
      - ../../:/home/postgres/context
      - db-queue:/var/lib/postgres/data
      - ./db-queue:/home/postgres/main
      - ./@certs:/home/postgres/raw-certs
    networks: 
      - project

  # --- SET UP ADMINER --- # 
  adminer:
    build: 
      context: ./adminer
      dockerfile: Dockerfile
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_adminer
    volumes: 
      - ./adminer/app:/var/www/html/
    networks:
      - project

  adminer-proxy: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_adminer-proxy
    env_file:
      - ../../../.env 
      - .env
    image: nginx:alpine
    volumes:
      - ./adminer/app:/var/www/html/
      - ./adminer/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on: 
      - adminer
    networks:
      - project

  # --- SET UP MAILPIT --- # 
  mailpit: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_mailpit
    build: 
      context: ./mailpit
      dockerfile: Dockerfile
    env_file:
      - ../../../.env 
      - .env
    environment:
      MAILPIT_UI_BIND: 0.0.0.0:8025 
      MAILPIT_SMTP_BIND: 0.0.0.0:1025
    volumes:
      - mailpit-data:/data
    networks: 
      - project

  mailpit-proxy: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_mailpit-proxy
    env_file:
      - ../../../.env 
      - .env
    image: nginx:alpine
    volumes:
      - ./mailpit/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - mailpit
    networks:
      - project

  # --- SET UP BACKEND --- # 
  backend: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_backend
    env_file:
      - ../../../.env 
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /home/app/source
    command: sh /home/app/main/start.sh
    volumes: 
      - ../../../source/backend:/home/app/source
      - ./backend:/home/app/main/
    depends_on: 
      - db-main
      - db-cache
      - db-queue
    networks:
      - project

  backend-proxy: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_backend-proxy
    env_file:
      - ../../../.env 
      - .env
    image: nginx:alpine
    volumes:
      - ./backend/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - backend
    networks:
      - project

# --- SETUP NETWORKS --- #
networks:
  project:
    driver: bridge

# --- SETUP VOLUMES --- # 
volumes: 
  db-main:  
    driver: local 
  db-cache: 
    driver: local 
  db-queue: 
    driver: local
  mailpit-data:
    driver: local