name: ${PROJECT_MODE}-${PROJECT_NAME} 

services: 
  # --- MAIN DATABASE CONFIGURATION --- # 
  db-main: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_db-main
    build: 
      context: ./db-main
      dockerfile: Dockerfile
      args: 
        DB_MAIN_VERSION: ${DB_MAIN_VERSION}
    restart: unless-stopped 
      
    env_file:
      - ../../../.env 
      - .env
    user: root 
    command: sh /home/postgres/main/start.sh
    volumes: 
      - ../../:/home/postgres/context
      - db-main:/var/lib/postgres/data
      - ./db-main:/home/postgres/main
      - ./@certs:/home/postgres/raw-certs
    networks: 
      - project

  # --- CACHE DATABASE CONFIGURATION --- # 
  db-cache: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_db-cache
    build: 
      context: ./db-cache
      dockerfile: Dockerfile
      args: 
        DB_CACHE_VERSION: ${DB_CACHE_VERSION}
    restart: unless-stopped 
    env_file:
      - ../../../.env 
      - .env
    user: root 
    command: sh /home/postgres/main/start.sh
    volumes: 
      - ../../:/home/postgres/context
      - db-cache:/var/lib/postgres/data
      - ./db-cache:/home/postgres/main
      - ./@certs:/home/postgres/raw-certs
    networks: 
      - project

  # --- QUEUE DATABASE CONFIGURATION --- # 
  db-queue: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_db-queue
    build: 
      context: ./db-queue
      dockerfile: Dockerfile
      args: 
        DB_QUEUE_VERSION: ${DB_QUEUE_VERSION}
    restart: unless-stopped 
    env_file:
      - ../../../.env 
      - .env
    user: root 
    command: sh /home/postgres/main/start.sh
    volumes: 
      - ../../:/home/postgres/context
      - db-queue:/var/lib/postgres/data
      - ./db-queue:/home/postgres/main
      - ./@certs:/home/postgres/raw-certs
    networks: 
      - project

  # --- SET UP ADMINER --- # 
  adminer:
    build: 
      context: ./adminer
      dockerfile: Dockerfile
      args: 
        ADMINER_PHP_VERSION: ${ADMINER_PHP_VERSION}
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_adminer
    volumes: 
      - ./adminer/app:/var/www/html/
    networks:
      - project

  adminer-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_adminer-server
    env_file:
      - ../../../.env 
      - .env
    image: ${ADMINER_NGINX_VERSION}
    volumes:
      - ./adminer/app:/var/www/html/
      - ./adminer/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on: 
      - adminer
    networks:
      - project

  # --- SET UP MAILPIT --- # 
  mailpit: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_mailpit
    build:
      context: ./mailpit
      dockerfile: Dockerfile
      args: 
        MAILPIT_VERSION: ${MAILPIT_VERSION}
    env_file:
      - ../../../.env 
      - .env
    environment: 
      - MP_SMTP_TLS_CERT=/certs/mailpit.crt
      - MP_SMTP_TLS_KEY=/certs/mailpit.key
      - MP_SMTP_REQUIRE_TLS=false
    volumes:
      - mailpit-data:/data
      - ./@certs:/certs
    networks: 
      - project

  mailpit-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_mailpit-server
    env_file:
      - ../../../.env 
      - .env
    image: ${MAILPIT_NGINX_VERSION}
    volumes:
      - ./mailpit/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - mailpit
    networks:
      - project

  # --- SET UP EXIM --- # 
  exim-server:
    build:
      context: ./exim
      dockerfile: Dockerfile 
      args: 
        EXIM_UBUNTU_VERSION: ${EXIM_UBUNTU_VERSION}
    env_file:
      - ../../../.env 
      - .env
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_exim-server
    user: root
    command: sh /home/exim/main/start.sh
    volumes: 
      - ./exim/exim.conf:/etc/exim4/exim4.conf
      - exim-logs:/var/log/exim4
      - exim-queue:/var/spool/exim4
      - exim-certs:/home/exim/certs
      - ./exim/:/home/exim/main
      - ./@certs:/certs
      - ./exim/auth/:/etc/exim4/auth
    depends_on:
      - mailpit
    networks: 
      - project

  # --- SET UP BACKEND --- # 
  backend: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_backend
    env_file:
      - ../../../.env 
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args: 
        BACKEND_PHP_VERSION: ${BACKEND_PHP_VERSION}
    working_dir: /home/app/source
    command: sh /home/app/main/start.sh
    volumes: 
      - ../../../source/backend:/home/app/source
      - ./backend:/home/app/main/
      - ./@certs:/certs
    depends_on: 
      - db-main
      - db-cache
      - db-queue
    networks:
      - project

  backend-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_backend-server
    env_file:
      - ../../../.env 
      - .env
    image: ${BACKEND_NGINX_VERSION}
    volumes:
      - ../../../source/backend:/home/app/source
      - ./backend:/home/app/main/
      - ./backend/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - backend
    networks:
      - project

  # --- SET UP QUEUE ---  #
  queue: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_queue
    env_file:
      - ../../../.env 
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args: 
        BACKEND_PHP_VERSION: ${BACKEND_PHP_VERSION}
    working_dir: /home/app/source
    command: sh /home/app/main/start.sh
    volumes: 
      - ../../../source/backend:/home/app/source
      - ./queue:/home/app/main/
    depends_on: 
      - db-main
      - db-cache
      - db-queue
      - backend-server
    networks:
      - project
      
  # --- SET UP FRONTEND (WEB) --- # 
  frontend-web-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_frontend-web-server
    env_file:
      - ../../../.env 
      - .env
    image: ${FRONTEND_WEB_NGINX_VERSION}
    volumes:
      - ../../../source/frontend-mobile:/home/app/source
      - ./frontend-web/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - backend-server
    networks:
      - project

  # --- SET UP FRONTEND (MOBILE) --- # 
  frontend-mobile-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_frontend-mobile-server
    env_file:
      - ../../../.env 
      - .env
    image: ${FRONTEND_MOBILE_NGINX_VERSION}
    volumes:
      - ../../../source/frontend-mobile:/home/app/source
      - ./frontend-mobile/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - backend-server
    networks:
      - project

  # --- SET UP WEBSOCKETS --- # 
  websockets: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_websockets
    env_file:
      - ../../../.env 
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args: 
        BACKEND_PHP_VERSION: ${BACKEND_PHP_VERSION}
    working_dir: /home/app/source
    command: sh /home/app/main/start.sh
    volumes: 
      - ../../../source/backend:/home/app/source
      - ./websockets:/home/app/main/
    depends_on: 
      - db-cache
      - db-main
      - db-queue
      - backend-server
    networks:
      - project

  websockets-server: 
    container_name: ${PROJECT_MODE}_${PROJECT_NAME}_websockets-server
    env_file:
      - ../../../.env 
      - .env
    image: ${WEBSOCKETS_NGINX_VERSION}
    volumes:
      - ./websockets/site.conf:/etc/nginx/conf.d/default.conf
      - ./@certs:/certs
    depends_on:
      - websockets
    networks:
      - project      

# --- SETUP NETWORKS --- #
networks:
  project:
    driver: bridge

# --- SETUP VOLUMES --- # 
volumes: 
  db-main:  
    driver: local 
  db-cache: 
    driver: local 
  db-queue: 
    driver: local
  postfix-data:
    driver: local
  mailpit-data: 
    driver: local
  exim-logs: 
    driver: local 
  exim-queue: 
    driver: local
  exim-certs:
    driver: local